---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lambda-user-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "watch", "list", "patch", "update"]
  - apiGroups: ["projectcalico.org"]
    resources: ["packetcaptures"]
    verbs: ["create","update","patch","get","list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lambda-user-cluster-role-binding
subjects:
- kind: User
  name: lambda
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: lambda-user-cluster-role
  apiGroup: rbac.authorization.k8s.io
